CREATE DATABASE IF NOT EXISTS QUANLYDIENTHOAI 
	CHARACTER SET utf8mb4 
  	COLLATE UTF8MB4_UNICODE_CI;
USE QUANLYDIENTHOAI;

CREATE TABLE NHACUNGCAP (
	MANCC VARCHAR (10) PRIMARY KEY,
	TENNHACC VARCHAR (100) NOT NULL,
	DIACHI VARCHAR (255),
	SODIENTHOAI VARCHAR (20)
);

CREATE TABLE DIENTHOAI (
	MADT VARCHAR (20) PRIMARY KEY,
	TENDT VARCHAR (100) NOT NULL,
	NAMSANXUAT INT NOT NULL,
	CAUHINH VARCHAR (255) NOT NULL,
	MANCC VARCHAR (10),
	HINHANH VARCHAR (255),
	FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC) ON DELETE SET NULL
);

INSERT INTO NHACUNGCAP(MANCC, TENNHACC, DIACHI, SODIENTHOAI) VALUES
('NCC01','Công ty A','Hà Nội','0123456789'),
('NCC02','Công ty B','HCM','0987654321');

INSERT INTO DIENTHOAI(MADT, TENDT, NAMSANXUAT, CAUHINH, MANCC, HINHANH) VALUES
('DT001','Model A1',2022,'RAM:4GB;ROM:64GB','NCC01','uploads/dt001.jpg'),
('DT002','Model B1',2021,'RAM:6GB;ROM:128GB','NCC02','uploads/dt002.jpg');